### ISSUE TITLE
Equal height giving error

### ISSUE THREAD

**Issue by since1976** [at-import/toolkit#17]
I'm getting an error while trying to use the equal height mixin.
I would like to create a single line to break up my two column layout using the below code

``` scss
.main{
    $widths: 25%;
    $colors: red;
    @include equal-height-columns($widths, $colors);
}
```

But am getting this error message in the terminal: `/Library/Ruby/Gems/1.8/gems/toolkit-0.2.6/stylesheets/toolkit/_equal-height-columns.scss:40 DEBUG: red, red 25%`

Any ideas what I might be doing wrong?

Details:
Sass 3.2.7
Compass 0.12.2
Breakpoint 1.3
