### ISSUE TITLE
Toolkit Error

### ISSUE THREAD

**Issue by lvthunder** [at-import/toolkit#35]
In my project I use @import toolkit-no-css, but in the css output I get what's below.  Does anyone have any suggestions?

``` scss
*, *:after, *:before {
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
  *behavior: url('../behaviors/box-sizing/boxsizing.php');
}

.comment__content, .breadcrumb, .action-links, .block--nav-bar .menu, .clearfix, .pager, .site-branding, .field--type-taxonomy-term-reference .field__items {
  /* for IE 6/7 */
  *zoom: expression(this.runtimeStyle.zoom="1", this.appendChild(document.createElement("br")).style.cssText="clear:both;font:0/0 serif");
  /* non-JS fallback */
  *zoom: 1;
}

.comment__content:before, .breadcrumb:before, .action-links:before, .block--nav-bar .menu:before, .clearfix:before, .pager:before, .site-branding:before, .field--type-taxonomy-term-reference .field__items:before, .comment__content:after, .breadcrumb:after, .action-links:after, .block--nav-bar .menu:after, .clearfix:after, .pager:after, .site-branding:after, .field--type-taxonomy-term-reference .field__items:after {
  content: ".";
  display: block;
  height: 0;
  overflow: hidden;
}

.comment__content:after, .breadcrumb:after, .action-links:after, .block--nav-bar .menu:after, .clearfix:after, .pager:after, .site-branding:after, .field--type-taxonomy-term-reference .field__items:after {
  clear: both;
}
```

**Comment by Snugug** [comment]
Please turn debug-info off and post your output CSS inside code fences (three ` at the start and end of your code, with scss immediately after the first three).

**Comment by lvthunder** [comment]
Here is the output

``` scss
@charset "IBM437";
@import url(http://fonts.googleapis.com/css?family=Maven+Pro:400,700);
@import url(http://fonts.googleapis.com/css?family=PT+Sans:400,700,400italic);
/* Loaded compass complete */
/* Loaded susy complete */
/* Loaded breakpoint complete */
/* line 36, ../../../../../../../../../Ruby193/lib/ruby/gems/1.9.1/gems/toolkit-1.3.7/stylesheets/toolkit/_box-sizing.scss */
*, *:after, *:before {
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
  *behavior: url('../behaviors/box-sizing/boxsizing.php');
}

/* line 77, ../../../../../../../../../Ruby193/lib/ruby/gems/1.9.1/gems/toolkit-1.3.7/stylesheets/toolkit/_clearfix.scss */
.comment__content, .breadcrumb, .action-links, .block--nav-bar .menu, .clearfix, .pager, .site-branding, .field--type-taxonomy-term-reference .field__items {
  /* for IE 6/7 */
  *zoom: expression(this.runtimeStyle.zoom="1", this.appendChild(document.createElement("br")).style.cssText="clear:both;font:0/0 serif");
  /* non-JS fallback */
  *zoom: 1;
}
/* line 44, ../../../../../../../../../Ruby193/lib/ruby/gems/1.9.1/gems/toolkit-1.3.7/stylesheets/toolkit/_clearfix.scss */
.comment__content:before, .breadcrumb:before, .action-links:before, .block--nav-bar .menu:before, .clearfix:before, .pager:before, .site-branding:before, .field--type-taxonomy-term-reference .field__items:before, .comment__content:after, .breadcrumb:after, .action-links:after, .block--nav-bar .menu:after, .clearfix:after, .pager:after, .site-branding:after, .field--type-taxonomy-term-reference .field__items:after {
  content: ".";
  display: block;
  height: 0;
  overflow: hidden;
}
/* line 51, ../../../../../../../../../Ruby193/lib/ruby/gems/1.9.1/gems/toolkit-1.3.7/stylesheets/toolkit/_clearfix.scss */
.comment__content:after, .breadcrumb:after, .action-links:after, .block--nav-bar .menu:after, .clearfix:after, .pager:after, .site-branding:after, .field--type-taxonomy-term-reference .field__items:after {
  clear: both;
}

/* Loaded external libraries complete */
/**
 * $ISLAND
 */
/* line 5, ../sass/partials/utility/abstractions/_island.scss */
.comment__content {
  display: block;
  margin-bottom: 18px;
}
/* line 11, ../sass/partials/utility/abstractions/_island.scss */
.comment__content > :last-child, .comment__content > :last-child {
  margin-bottom: 0;
}

/* line 16, ../sass/partials/utility/abstractions/_island.scss */
.comment__content {
  padding: 18px 1em;
}

/**
 * $ARROW
 */
/**
 * $HLIST
 */
/* line 4, ../sass/partials/utility/abstractions/_hlist.scss */
.breadcrumb, .action-links, .block--nav-bar .menu {
  list-style: none;
  margin: 0;
  padding: 0;
}
/* line 10, ../sass/partials/utility/abstractions/_hlist.scss */
.breadcrumb > li, .action-links > li, .block--nav-bar .menu > li {
  list-style: none;
}
/* line 14, ../sass/partials/utility/abstractions/_hlist.scss */
.breadcrumb > li, .action-links > li, .block--nav-bar .menu > li,
.breadcrumb > li > a,
.action-links > li > a,
.block--nav-bar .menu > li > a {
  float: left;
}

/* Utilities Loaded */
/* line 36, ../../../../../../../../../Ruby193/lib/ruby/gems/1.9.1/gems/toolkit-1.3.7/stylesheets/toolkit/_box-sizing.scss */
*, *:after, *:before {
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
  *behavior: url('../behaviors/box-sizing/boxsizing.php');
}

/**
 * $FONT-FACE
 */
/**
 * $BASE-TYPOGRAPHY
 */
/* line 10, ../sass/partials/base/_typography.scss */
html {
  font-size: 14px;
  font-family: "PT Sans", Helvetica, Arial, sans-serif;
  color: #222222;
}

/**
 * $LINKS
 */
/* line 19, ../sass/partials/base/_typography.scss */
a {
  color: #e4621c;
}
/* line 23, ../sass/partials/base/_typography.scss */
a:hover, a:focus {
  color: #000;
  text-decoration: none;
}

/**
 * $HEADINGS
 */
/* line 37, ../sass/partials/base/_typography.scss */
h1, .alpha,
h2, .beta, .site-branding__name,
h3, .gamma,
h4, .delta, caption,
h5, .epsilon,
h6, .zeta {
  margin-top: 0;
  margin-bottom: 0.2em;
  color: #464a4e;
  font-family: "Maven Pro", Helvetica, Arial, sans-serif;
  line-height: 1.2em;
  text-transform: uppercase;
}
/* line 45, ../sass/partials/base/_typography.scss */
h1 a, .alpha a,
h2 a, .beta a, .site-branding__name a,
h3 a, .gamma a,
h4 a, .delta a, caption a,
h5 a, .epsilon a,
h6 a, .zeta a {
  color: inherit;
  text-decoration: none;
}

/* line 51, ../sass/partials/base/_typography.scss */
h1, .alpha {
  font-size: 55px;
  font-size: 3.4375rem;
  font-weight: 700;
}

/* line 55, ../sass/partials/base/_typography.scss */
h2, .beta, .site-branding__name {
  font-size: 34px;
  font-size: 2.125rem;
  font-weight: 700;
  color: #077dc3;
}

/* line 60, ../sass/partials/base/_typography.scss */
h3, .gamma {
  font-size: 21px;
  font-size: 1.3125rem;
}

/* line 63, ../sass/partials/base/_typography.scss */
h4, .delta, caption {
  font-size: 18px;
  font-size: 1.125rem;
}

/* line 66, ../sass/partials/base/_typography.scss */
h5, .epsilon {
  font-size: 16px;
  font-size: 1rem;
  font-weight: 700;
}

/* line 70, ../sass/partials/base/_typography.scss */
h6, .zeta {
  font-size: 16px;
  font-size: 1rem;
  color: #077dc3;
}

/**
 * $PARAGRAPHS
 */
/* line 79, ../sass/partials/base/_typography.scss */
p,
blockquote {
  margin: 0;
  margin-bottom: 1em;
}

/* line 83, ../sass/partials/base/_typography.scss */
p + img {
  float: left;
  margin-right: 1em;
}

/**
 * $QUOTES
 */
/* line 91, ../sass/partials/base/_typography.scss */
blockquote {
  padding: 1em 1.5em;
  border: 1px solid #064771;
  border-left-width: 1.2em;
  font-style: italic;
  color: #064771;
}
/* line 99, ../sass/partials/base/_typography.scss */
blockquote p {
  margin: 0;
}

/* line 104, ../sass/partials/base/_typography.scss */
q {
  font-style: italic;
}

/**
 * $MARKS
 */
/* line 112, ../sass/partials/base/_typography.scss */
mark,
.marker {
  padding: 0.1em 0.5em;
  background: #52b1ea;
  color: #FFF;
  font-size: 12px;
  font-size: 0.75rem;
  text-transform: capitalize;
  -webkit-border-radius: 10px;
  -moz-border-radius: 10px;
  -ms-border-radius: 10px;
  -o-border-radius: 10px;
  border-radius: 10px;
}

/**
 * $BUTTONS
 */
/* Base Button */
/* line 5, ../sass/partials/base/_buttons.scss */
.button {
  display: inline-block;
  height: 2.2em;
  margin: 0;
  padding: 0 1.2em;
  background-color: #222222;
  border: none;
  color: #FFF;
  font-weight: 700;
  font-family: inherit;
  font-size: 100%;
  line-height: 2.2;
  letter-spacing: 0.15em;
  text-transform: uppercase;
  vertical-align: middle;
  white-space: nowrap;
  overflow: visible;
  cursor: pointer;
}
/* line 32, ../sass/partials/base/_buttons.scss */
.button, .button:hover, .button:active, .button:focus, .button:visited {
  text-decoration: none;
}
/* line 36, ../sass/partials/base/_buttons.scss */
.button:hover {
  background-color: #6a7076;
}
/* line 41, ../sass/partials/base/_buttons.scss */
.button:active, .button:focus {
  outline: none;
  box-shadow: 0 0 5px rgba(0, 0, 0, 0.5) inset;
}
/* line 46, ../sass/partials/base/_buttons.scss */
.button::-moz-focus-inner {
  border: 0;
  padding: 0;
}

/* Fill width of container */
/* line 53, ../sass/partials/base/_buttons.scss */
.button--full {
  width: 100%;
  padding-right: 0;
  padding-left: 0;
  text-align: center;
}

/* Inherit sizing from parent  */
/* line 61, ../sass/partials/base/_buttons.scss */
.button--natural {
  vertical-align: baseline;
  font-size: inherit;
  line-height: inherit;
  height: auto;
  padding-right: 0.5em;
  padding-left: 0.5em;
}

/* Button Functions */
/* line 71, ../sass/partials/base/_buttons.scss */
.button--primary {
  background-color: #e4621c;
}

/* line 75, ../sass/partials/base/_buttons.scss */
.button--secondary {
  background-color: transparent;
  border: 1px solid #52b1ea;
  color: #52b1ea;
}
/* line 80, ../sass/partials/base/_buttons.scss */
.button--secondary:hover {
  border-color: #6a7076;
  background-color: transparent;
  color: #6a7076;
}

/* line 87, ../sass/partials/base/_buttons.scss */
.button--positive {
  background-color: #4a993e;
}
/* line 89, ../sass/partials/base/_buttons.scss */
.button--positive:hover {
  background-color: #38752f;
}

/* line 94, ../sass/partials/base/_buttons.scss */
.button--negative {
  background-color: #b33630;
}
/* line 96, ../sass/partials/base/_buttons.scss */
.button--negative:hover {
  background-color: #8b2a25;
}

/* line 104, ../sass/partials/base/_buttons.scss */
.button--disabled,
.button--disabled:hover,
.button--disabled:active,
.button--disabled:focus {
  background-color: #ddd;
  color: #777;
  cursor: default;
  box-shadow: none;
}

/* Adjacent buttons should have some space between them. */
/* line 113, ../sass/partials/base/_buttons.scss */
.button + .button,
.button + a {
  margin-left: 1em;
}

/**
 * $TABLES
 */
/* line 4, ../sass/partials/base/_tables.scss */
table {
  width: 100%;
  margin-bottom: 18px;
}

/* line 9, ../sass/partials/base/_tables.scss */
th {
  padding: 0.5em 1em;
  background-color: #077dc3;
  color: #FFF;
}
/* line 15, ../sass/partials/base/_tables.scss */
th a,
th a.active {
  color: #FFF;
}
/* line 18, ../sass/partials/base/_tables.scss */
th a img,
th a.active img {
  margin: 2px 3px;
}

/* line 23, ../sass/partials/base/_tables.scss */
td {
  padding: 0.5em 1em;
}

/* line 27, ../sass/partials/base/_tables.scss */
tr.odd {
  background: #e7f1f5;
}

/* line 30, ../sass/partials/base/_tables.scss */
tr.even {
  background: #f6fafb;
}

/**
 * $FORM-ITEM
 */
/* line 4, ../sass/partials/base/forms/_form-items.scss */
.form-item {
  color: #6a7076;
}
/* line 7, ../sass/partials/base/forms/_form-items.scss */
.form-item label {
  margin-bottom: 0.4em;
}
/* line 12, ../sass/partials/base/forms/_form-items.scss */
.form-item .form-select,
.form-item .form-text,
.form-item .form-textarea {
  width: 100%;
  padding: 1em;
  background-color: #FFF;
  border: 1px solid #dddddd;
  color: #6a7076;
  vertical-align: middle;
}
/* line 20, ../sass/partials/base/forms/_form-items.scss */
.form-item .description {
  margin-top: 0.2em;
  font-style: italic;
}

/* line 29, ../sass/partials/base/forms/_form-items.scss */
.container-inline .form-select,
.container-inline .form-text,
.container-inline .form-textarea {
  width: auto;
}

/* line 37, ../sass/partials/base/forms/_form-items.scss */
select:focus,
input:focus,
textarea:focus {
  -webkit-box-shadow: 0 0 4px 1px rgba(236, 145, 96, 0.3);
  -moz-box-shadow: 0 0 4px 1px rgba(236, 145, 96, 0.3);
  box-shadow: 0 0 4px 1px rgba(236, 145, 96, 0.3);
  outline: 1px solid #ec9160;
}

/**
 * $PASSWORD-INDICATOR
 */
/* line 4, ../sass/partials/base/forms/_passwords.scss */
.password-indicator {
  height: 0.8em;
  background: none;
  border: 1px solid #dddddd;
}
/* line 9, ../sass/partials/base/forms/_passwords.scss */
.password-indicator .indicator {
  background: #efa47b;
}

/* line 14, ../sass/partials/base/forms/_passwords.scss */
.password-strength-title {
  margin-bottom: 0.2em;
}

/**
 * $FIELDSETS
 */
/* line 4, ../sass/partials/base/forms/_fieldsets.scss */
.form-wrapper {
  margin-bottom: 18px;
}

/* line 8, ../sass/partials/base/forms/_fieldsets.scss */
fieldset {
  margin-left: 0;
  margin-right: 0;
  padding: 9px 1em 18px 1em;
  border-color: #dddddd;
}

/* line 16, ../sass/partials/base/forms/_fieldsets.scss */
legend {
  font-size: 18px;
  font-size: 1.125rem;
  padding: 0 0.8em;
  color: #6a7076;
}

/* line 22, ../sass/partials/base/forms/_fieldsets.scss */
.fieldset-description {
  margin-bottom: 9px;
  color: #6a7076;
  font-style: italic;
}

/* line 28, ../sass/partials/base/forms/_fieldsets.scss */
.vertical-tabs fieldset.vertical-tabs-pane {
  padding: 18px 1em;
}

/* line 1, ../sass/partials/base/_media.scss */
img, media {
  max-width: 100%;
  height: auto;
  vertical-align: top;
}

/* Base Loaded */
/* Layout Loaded */
/**
 * $PAGER
 */
/* line 8, ../sass/partials/components/misc/_pager.scss */
.pager__item {
  display: block;
  float: left;
  margin: 0.1em;
  padding: 0;
}

/* line 17, ../sass/partials/components/misc/_pager.scss */
.pager__item a,
.pager__item--current,
.pager__item--ellipsis {
  display: block;
  padding: 0.5em 0.8em;
  border: 1px solid #6a7076;
  color: #6a7076;
  text-decoration: none;
}

/* line 24, ../sass/partials/components/misc/_pager.scss */
.pager__item a:hover {
  background-color: #e4621c;
  border-color: #e4621c;
  color: #FFF;
}

/* line 29, ../sass/partials/components/misc/_pager.scss */
.pager__item--current {
  border-color: #e4621c;
  color: #e4621c;
}

/* line 33, ../sass/partials/components/misc/_pager.scss */
.pager__item--ellipsis {
  border: none;
}

/**
 * $PROGRESS
 */
/* line 5, ../sass/partials/components/misc/_progress.scss */
.progress .bar {
  background-color: #dddddd;
  border-color: #6a7076;
  -webkit-border-radius: 0;
  -moz-border-radius: 0;
  -ms-border-radius: 0;
  -o-border-radius: 0;
  border-radius: 0;
}
/* line 10, ../sass/partials/components/misc/_progress.scss */
.progress .filled {
  background: #077dc3;
}

/**
 * $MESSAGES
 */
/* line 4, ../sass/partials/components/misc/_messages.scss */
.messages {
  padding-left: 10px;
  margin-bottom: 18px;
}

/* line 9, ../sass/partials/components/misc/_messages.scss */
.messages--status {
  color: #077dc3;
  background: #ccebfd;
  border-color: #38b0f8;
}

/* line 15, ../sass/partials/components/misc/_messages.scss */
.messages--warning {
  color: #d6c460;
  background: white;
  border-color: #ebe2b1;
}

/* line 21, ../sass/partials/components/misc/_messages.scss */
.messages--error {
  color: #b33630;
  background: #f9eae9;
  border-color: #d97570;
}

/**
 * $SITE-BRANDING
 */
/* line 4, ../sass/partials/components/misc/_site-branding.scss */
.site-branding {
  padding: 1em 0;
}

/* line 10, ../sass/partials/components/misc/_site-branding.scss */
.site-branding__name,
.site-branding__logo {
  display: block;
  float: left;
}

/* line 15, ../sass/partials/components/misc/_site-branding.scss */
.site-branding__logo {
  width: 50px;
  margin-right: 1em;
}

/* line 19, ../sass/partials/components/misc/_site-branding.scss */
.site-branding__name {
  color: #FFF;
  text-decoration: none;
}
/* line 24, ../sass/partials/components/misc/_site-branding.scss */
.site-branding__name:hover {
  color: #064771;
}

/**
 * $SECTION-TITLE
 */
/* line 4, ../sass/partials/components/misc/_section-title.scss */
.section-title {
  padding-bottom: 0.5em;
  margin-bottom: 18px;
  border-bottom: 1px solid #bcd8e3;
}

/**
 * $BORDER-LIST
 */
/* line 4, ../sass/partials/components/misc/_border-list.scss */
.border-list {
  padding: 0;
  list-style: none;
}
/* line 9, ../sass/partials/components/misc/_border-list.scss */
.border-list li {
  padding-bottom: 1em;
  margin-bottom: 1em;
  border-bottom: 1px solid #dddddd;
}
/* line 14, ../sass/partials/components/misc/_border-list.scss */
.border-list li:last-child {
  padding-bottom: 0;
  margin-bottom: 0;
  border-bottom: none;
}

/**
 * $FILTER-TIPS
 */
/* line 4, ../sass/partials/components/forms/_filter-tips.scss */
.filter-wrapper {
  background-color: #FFF;
}

/**
 * $SEARCH-FORM
 */
/* line 5, ../sass/partials/components/forms/_search-form.scss */
.search-block-form .form-text {
  width: auto;
  padding: 0.4em;
}

/**
 * $PASSWORD-CONFIRM
 */
/* line 5, ../sass/partials/components/forms/_password-confirm.scss */
div.password-indicator,
div.password-confirm {
  margin-top: 0;
}

/* line 9, ../sass/partials/components/forms/_password-confirm.scss */
div.password-indicator {
  margin-bottom: 0.4em;
}

/**
 * $COLLAPSIBLE
 */
/* line 4, ../sass/partials/components/forms/_collapsible.scss */
html.js fieldset.collapsible {
  padding: 0;
  border: none;
}
/* line 8, ../sass/partials/components/forms/_collapsible.scss */
html.js fieldset.collapsible legend {
  width: 100%;
  padding: 0;
}
/* line 12, ../sass/partials/components/forms/_collapsible.scss */
html.js fieldset.collapsible .fieldset-legend {
  padding: 0;
  background: none;
}
/* line 16, ../sass/partials/components/forms/_collapsible.scss */
html.js fieldset.collapsible .fieldset-legend .summary {
  float: right;
}
/* line 20, ../sass/partials/components/forms/_collapsible.scss */
html.js fieldset.collapsible .fieldset-title {
  display: block;
  padding: 1em;
  background-color: #dddddd;
  color: #077dc3;
  text-decoration: none;
}
/* line 29, ../sass/partials/components/forms/_collapsible.scss */
html.js fieldset.collapsible .fieldset-title:hover {
  background-color: #d9e9ef;
  color: #064771;
}
/* line 34, ../sass/partials/components/forms/_collapsible.scss */
html.js fieldset.collapsible .fieldset-wrapper {
  padding: 18px 1em;
  border: 1px solid #dddddd;
}

/* line 40, ../sass/partials/components/forms/_collapsible.scss */
html.js fieldset.collapsed {
  height: 3.7em;
}

/**
 * $NODE
 */
/* line 4, ../sass/partials/components/node/_node.scss */
.node--teaser {
  margin-bottom: 18px;
}

/* line 8, ../sass/partials/components/node/_node.scss */
.node__links {
  margin-bottom: 18px;
}

/**
 * $NODE-BASIC-PAGE
 */
/* line 5, ../sass/partials/components/node/_node-article.scss */
.node--article .field--name-field-image {
  float: left;
  margin: 0 2em 1em 0;
}

/**
 * $FIELD
 */
/* line 4, ../sass/partials/components/fields/_field.scss */
.field {
  margin-bottom: 1em;
}

/**
 * $FIELD-TAXONOMY-TERM
 */
/* line 8, ../sass/partials/components/fields/_field-taxonomy-term.scss */
.field--type-taxonomy-term-reference .field__item {
  float: left;
  margin-right: 0.5em;
}

/**
 * $BREADCRUMB
 */
/* line 7, ../sass/partials/components/menus/_breadcrumb.scss */
.breadcrumb li {
  padding-right: 0.4em;
}
/* line 10, ../sass/partials/components/menus/_breadcrumb.scss */
.breadcrumb li:after {
  content: "»";
  padding-left: 0.4em;
  vertical-align: baseline;
}
/* line 15, ../sass/partials/components/menus/_breadcrumb.scss */
.breadcrumb li:last-child:after {
  content: "";
}
/* line 20, ../sass/partials/components/menus/_breadcrumb.scss */
.breadcrumb a {
  text-decoration: none;
}

/**
 * $ACTION-LINKS
 */
/* line 4, ../sass/partials/components/menus/_action-links.scss */
.action-links {
  margin-bottom: 18px;
}
/* line 8, ../sass/partials/components/menus/_action-links.scss */
.action-links li {
  padding-left: 16px;
  background: transparent url('../images/../images/plus-blue.png?1374038266') left center no-repeat;
}
/* line 13, ../sass/partials/components/menus/_action-links.scss */
.action-links li a {
  color: #077dc3;
  text-decoration: none;
}
/* line 17, ../sass/partials/components/menus/_action-links.scss */
.action-links li a:hover {
  font-weight: 700;
}

/**
 * $NAV-BAR
 */
/* line 9, ../sass/partials/components/blocks/_nav-bar.scss */
.block--nav-bar a {
  display: block;
  padding: 1em;
  border-left: 1px solid #FFF;
  font-size: 20px;
  font-size: 1.25rem;
  text-transform: uppercase;
  text-decoration: none;
  color: #FFF;
}
/* line 21, ../sass/partials/components/blocks/_nav-bar.scss */
.block--nav-bar li:last-child a {
  border-right: 1px solid #FFF;
}

/**
 * $COMMENT-WRAPPER
 */
/* line 4, ../sass/partials/components/comments/_comment-wrapper.scss */
.comment-wrapper {
  padding: 18px 1em;
  background-color: #d9e9ef;
}

/**
 * $COMMENT
 */
/* line 4, ../sass/partials/components/comments/_comment.scss */
.comment__info {
  margin-top: 18px;
  margin-bottom: 18px;
}
/* line 8, ../sass/partials/components/comments/_comment.scss */
.comment__info .username {
  margin-bottom: 9px;
  color: #52b1ea;
  text-transform: uppercase;
  text-decoration: none;
}
/* line 15, ../sass/partials/components/comments/_comment.scss */
.comment__info .username:hover {
  text-decoration: underline;
}

/* line 21, ../sass/partials/components/comments/_comment.scss */
.comment__content {
  background-color: #FFF;
}

/* line 27, ../sass/partials/components/comments/_comment.scss */
.comment__submitted {
  display: inline;
}

@media (min-width: 44em) {
  /* line 32, ../sass/partials/components/comments/_comment.scss */
  .comment__info {
    float: left;
    width: 25%;
    text-align: center;
  }
  /* line 38, ../sass/partials/components/comments/_comment.scss */
  .comment__info .user-picture {
    width: 70%;
    margin: 0 auto 9px auto;
  }
  /* line 42, ../sass/partials/components/comments/_comment.scss */
  .comment__info .username {
    display: block;
  }

  /* line 47, ../sass/partials/components/comments/_comment.scss */
  .comment__content {
    float: right;
    width: 70%;
    margin-left: 5%;
    position: relative;
    background: white;
  }
  /* line 28, ../sass/partials/utility/abstractions/_arrow.scss */
  .comment__content:after, .comment__content:before {
    right: 100%;
    border: solid transparent;
    content: " ";
    height: 0;
    width: 0;
    position: absolute;
    pointer-events: none;
  }
  /* line 50, ../sass/partials/utility/abstractions/_arrow.scss */
  .comment__content:after {
    border-color: transparent;
    border-right-color: white;
    border-width: 20px;
    top: 50%;
    margin-left: -20px;
  }
  /* line 54, ../sass/partials/components/comments/_comment.scss */
  .comment__content:after {
    top: 20px;
  }

  /* line 59, ../sass/partials/components/comments/_comment.scss */
  .comment__submitted {
    display: block;
    margin-bottom: 9px;
  }
}
```

**Comment by Snugug** [comment]
Woah there, that's a little bit too much. I'm only interested in what you're getting from Toolkit, not your entire output CSS. After taking a look at both examples you've given, you are definitely importing Toolkit twice, which for extendable classes will produce duplicate CSS. It also looks like in one place you're importing `'toolkit-no-css'` while in another place you're getting just `'toolkit'`. This is where 

``` scss
*, *:after, *:before {
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
  *behavior: url('../behaviors/box-sizing/boxsizing.php');
}
```

is coming from. As for the clearfix stuff, well you're calling the clearfix mixin somewhere (well actually lots of somewheres) and that's printing CSS because you've asked it to.
