### ISSUE TITLE
box-sizing: border-box; not applied in all browsers :(

### ISSUE THREAD

**Issue by mikl** [at-import/toolkit#40]
I'm getting this in my compiled CSS 

``` css
/* line 36, ../../../../../../../../gems/gems/toolkit-1.3.8/stylesheets/toolkit/_box-sizing.scss */
*, *:after, *:before {
  box-sizing: border-box;
}
```

Which does not include the `-moz` and `-webkit` prefixed versions that are otherwise recommended: http://www.paulirish.com/2012/box-sizing-border-box-ftw/

I think it usually does, so there might be some version issue here. For this instance, I have the following installed:
- breakpoint (2.0.7)
- bundler (1.3.5)
- chunky_png (1.2.8)
- color-schemer (0.2.7)
- compass (0.12.2)
- compass-blend-modes (0.0.2)
- compass-normalize (1.4.3)
- fssm (0.2.10)
- modular-scale (1.0.6)
- sass (3.2.11)
- sassy-buttons (0.2.6)
- sassy-math (1.5)
- sassy-strings (1.0.0)
- singularitygs (1.1.2)
- toolkit (1.3.8)
