### ISSUE TITLE
Consider updating kickstart's box-sizing code.

### ISSUE THREAD

**Issue by finteractive** [at-import/toolkit#69]
Consider implementing the "slightly better" box sizing suggested by Chris Coyier.
http://css-tricks.com/inheriting-box-sizing-probably-slightly-better-best-practice/

``` scss
html {
  box-sizing: border-box;
}

*, *:before, *:after {
  box-sizing: inherit;
}
```

I've run into the need to fight the inheritance for 3rd party libraries that expect box-sizing: content-box and this technique removed the need to define box-sizing: content-box multiple times for elements nested inside a larger component.
